# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(730, 443)
        self.centralwidget = QtWidgets.QWidget(parent=mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 730, 21))
        self.menubar.setObjectName("menubar")
        self.menuArticulos = QtWidgets.QMenu(parent=self.menubar)
        self.menuArticulos.setObjectName("menuArticulos")
        self.menuBodegas = QtWidgets.QMenu(parent=self.menubar)
        self.menuBodegas.setObjectName("menuBodegas")
        mainWindow.setMenuBar(self.menubar)
        self.mnuItems = QtGui.QAction(parent=mainWindow)
        self.mnuItems.setObjectName("mnuItems")
        self.mnuWarehouse = QtGui.QAction(parent=mainWindow)
        self.mnuWarehouse.setObjectName("mnuWarehouse")
        self.mnuDistribuitors = QtGui.QAction(parent=mainWindow)
        self.mnuDistribuitors.setObjectName("mnuDistribuitors")
        self.mnuItemsByWarehouse = QtGui.QAction(parent=mainWindow)
        self.mnuItemsByWarehouse.setObjectName("mnuItemsByWarehouse")
        self.mnuItemsByDistributor = QtGui.QAction(parent=mainWindow)
        self.mnuItemsByDistributor.setObjectName("mnuItemsByDistributor")
        self.menuArticulos.addAction(self.mnuItems)
        self.menuArticulos.addSeparator()
        self.menuArticulos.addAction(self.mnuWarehouse)
        self.menuArticulos.addSeparator()
        self.menuArticulos.addAction(self.mnuDistribuitors)
        self.menuBodegas.addAction(self.mnuItemsByWarehouse)
        self.menuBodegas.addSeparator()
        self.menuBodegas.addAction(self.mnuItemsByDistributor)
        self.menubar.addAction(self.menuArticulos.menuAction())
        self.menubar.addAction(self.menuBodegas.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Menu principal"))
        self.menuArticulos.setTitle(_translate("mainWindow", "Inicio"))
        self.menuBodegas.setTitle(_translate("mainWindow", "Inventario"))
        self.mnuItems.setText(_translate("mainWindow", "Articulos"))
        self.mnuWarehouse.setText(_translate("mainWindow", "Bodegas"))
        self.mnuDistribuitors.setText(_translate("mainWindow", "Distribuidores"))
        self.mnuItemsByWarehouse.setText(_translate("mainWindow", "Asignar articulo a bodega"))
        self.mnuItemsByDistributor.setText(_translate("mainWindow", "Asignar articulo a distribuidor"))
