# Form implementation generated from reading ui file 'items.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(487, 181)
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 171, 20))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 80, 111, 20))
        self.label_2.setObjectName("label_2")
        self.txtDescription = QtWidgets.QLineEdit(parent=Dialog)
        self.txtDescription.setGeometry(QtCore.QRect(200, 130, 121, 21))
        self.txtDescription.setObjectName("txtDescription")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 161, 20))
        self.label.setObjectName("label")
        self.txtItem = QtWidgets.QLineEdit(parent=Dialog)
        self.txtItem.setGeometry(QtCore.QRect(200, 30, 120, 20))
        self.txtItem.setObjectName("txtItem")
        self.txtId = QtWidgets.QLineEdit(parent=Dialog)
        self.txtId.setGeometry(QtCore.QRect(200, 80, 120, 20))
        self.txtId.setObjectName("txtId")
        self.btnSave = QtWidgets.QPushButton(parent=Dialog)
        self.btnSave.setGeometry(QtCore.QRect(350, 30, 101, 23))
        self.btnSave.setObjectName("btnSave")
        self.btnBack = QtWidgets.QPushButton(parent=Dialog)
        self.btnBack.setGeometry(QtCore.QRect(350, 80, 101, 23))
        self.btnBack.setObjectName("btnBack")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Registro de Articulos"))
        self.label_3.setText(_translate("Dialog", "Cuantos articulos desea agregar?"))
        self.label_2.setText(_translate("Dialog", "Numero de ID:"))
        self.label.setText(_translate("Dialog", "Que articulo desea agregar?"))
        self.btnSave.setText(_translate("Dialog", "Guardar"))
        self.btnBack.setText(_translate("Dialog", "Volver"))
